server:
  port: 8083
  servlet:
    context-path: /story
    
    
spring: 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ls-ccb0bd59a5868bee6b025261b4d71f872d80da4a.clsn1el257cg.eu-central-1.rds.amazonaws.com:5432/postgres
    username: dbmasteruser
    password: Passw0rdStory123
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true 